services:
  postgres:
    image: postgres:17.0
    container_name: benchmark_psql_1
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - psql-db:/var/lib/postgresql/data

volumes:
  psql-db:
